version: "3.8"
services:
  mongo:
    image: mongo:6
    ports: ["27017:27017"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  api:
    build: ./api
    ports: ["3000:3000"]
    depends_on: [mongo, redis]
    environment:
      - MONGO_URI=mongodb://mongo:27017/droplater
      - REDIS_URL=redis://redis:6379
      - ADMIN_TOKEN=supersecret

  worker:
    build: ./worker
    depends_on: [mongo, redis]
    environment:
      - MONGO_URI=mongodb://mongo:27017/droplater
      - REDIS_URL=redis://redis:6379

  sink:
    build: ./sink
    ports: ["4000:4000"]
    depends_on: [redis]

  admin:
    build: ./admin
    ports: ["5173:5173"] # if using Vite
    depends_on: [api]
