version: '3.9'

services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  api:
    build: ./api
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    env_file:
      - ./.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/notes
      - REDIS_URL=redis://redis:6379
      - PORT=3000
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app

  worker:
    build: ./worker
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    env_file:
      - ./.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/notes
      - REDIS_URL=redis://redis:6379
      - QUEUE_NAME=deliver-notes
      - BACKOFF_MS=1000,5000,25000
    volumes:
      - ./worker:/usr/src/app

  sink:
    build: ./sink
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - ./.env
    environment:
      - PORT=4000
      - REDIS_URL=redis://redis:6379
      - SINK_FAIL=${SINK_FAIL}
    ports:
      - "4000:4000"
    volumes:
      - ./sink:/usr/src/app

volumes:
  mongo-data:
  redis-data:


